pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "royalnavy/vault-spring-boot-simple-crud-jpa:latest"
        PROJECT_DIR = "simple-crud-jpa"
    }
    
    stages {
        stage('checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/muhamadilhamh/vault-spring-boot-testing'
            }
        }
        stage('build & package') {
            steps {
                dir("${PROJECT_DIR}"){
                    sh 'mvn clean package -DskipTests'
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: "simple-crud-jpa/target/*.jar", fingerprint: true
                }
            }
        }
        stage('build docker image'){
            steps {
                dir("${PROJECT_DIR}"){
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }
        stage('push docker image'){
            steps {
                sh '''
                docker push ${DOCKER_IMAGE}
                docker logout
                '''
            }
        }
        stage('deploy via ansible'){
            steps {
                echo 'Deploying application on target server via ansible...'
                sh '''
                ansible-playbook -i /home/jenkins/ansible/inventories/inventory.ini /home/jenkins/ansible/playbooks/deploy-simple-crud-jpa.yaml \
                --extra-vars "image=${DOCKER_IMAGE}"
                '''
            }
        }
    }
    post {
        success {
            echo 'Application deployed successfully'
        }
        failure {
            echo 'Application deploy failed'
        }
    }
}